## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Identifying the column names
application_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN' , 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
value_cutoff = 500
application_types_to_replace = []

## Calculate the number of value counts for each application type
application_counts = application_df['APPLICATION_TYPE'].value_counts()

## Develop a list of application types to be replaced
for app_val, values in application_counts.items():
    if values < value_cutoff:
        application_types_to_replace.append(app_val)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
classification_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_filtered_count = classification_value_counts[classification_value_counts > 1]
classification_filtered_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
value_cutoff_mod = 1000
classifications_to_replace = []

## Calculate the number of value counts for each classification
classification_counts = application_df['CLASSIFICATION'].value_counts()

## Develop a list of classifications to be replaced
for cls_val, types in classification_counts.items():
    if types < value_cutoff_mod:
        classifications_to_replace.append(cls_val)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset ; choose test size to be 20 results
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_features = X_train.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
# Train the model
fit_model = nn.fit(X_train, y_train, epochs=50)

Epoch 1/50
858/858 [==============================] - 4s 3ms/step - loss: 85264.0312 - accuracy: 0.4852
Epoch 2/50
858/858 [==============================] - 2s 3ms/step - loss: 72822.6562 - accuracy: 0.4921
Epoch 3/50
858/858 [==============================] - 2s 3ms/step - loss: 57238.0508 - accuracy: 0.4979
Epoch 4/50
858/858 [==============================] - 2s 3ms/step - loss: 37102.2695 - accuracy: 0.4991
Epoch 5/50
858/858 [==============================] - 3s 3ms/step - loss: 13560.3389 - accuracy: 0.4887
Epoch 6/50
858/858 [==============================] - 3s 4ms/step - loss: 33117.1641 - accuracy: 0.5069
Epoch 7/50
858/858 [==============================] - 3s 3ms/step - loss: 24175.2207 - accuracy: 0.5155
Epoch 8/50
858/858 [==============================] - 2s 3ms/step - loss: 36564.7891 - accuracy: 0.4959
Epoch 9/50
858/858 [==============================] - 2s 3ms/step - loss: 14189.5752 - accuracy: 0.5044
Epoch 10/50
858/858 [==============================] - 2s 3ms/step - loss: 5967.5664 - accuracy: 0.4955
Epoch 11/50
858/858 [==============================] - 2s 3ms/step - loss: 10547.4629 - accuracy: 0.5187
Epoch 12/50
858/858 [==============================] - 3s 4ms/step - loss: 5885.6904 - accuracy: 0.5135
Epoch 13/50
858/858 [==============================] - 2s 3ms/step - loss: 1162.1991 - accuracy: 0.5163
Epoch 14/50
858/858 [==============================] - 2s 3ms/step - loss: 1280.3617 - accuracy: 0.5296
Epoch 15/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6388 - accuracy: 0.6336
Epoch 16/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6325 - accuracy: 0.6490
Epoch 17/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6314 - accuracy: 0.6508
Epoch 18/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6308 - accuracy: 0.6507
Epoch 19/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6306 - accuracy: 0.6507
Epoch 20/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6305 - accuracy: 0.6506
Epoch 21/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6305 - accuracy: 0.6506
Epoch 22/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6310 - accuracy: 0.6498
Epoch 23/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6304 - accuracy: 0.6496
Epoch 24/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6307 - accuracy: 0.6494
Epoch 25/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6290 - accuracy: 0.6544
Epoch 26/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6303 - accuracy: 0.6543
Epoch 27/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6354 - accuracy: 0.6468
Epoch 28/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6844 - accuracy: 0.5447
Epoch 29/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6816 - accuracy: 0.5599
Epoch 30/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 31/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6915 - accuracy: 0.5302
Epoch 32/50
858/858 [==============================] - 2s 2ms/step - loss: 0.6915 - accuracy: 0.5302
Epoch 33/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 34/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 35/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 36/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6915 - accuracy: 0.5302
Epoch 37/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 38/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6914 - accuracy: 0.5294
Epoch 39/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6917 - accuracy: 0.5302
Epoch 40/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 41/50
858/858 [==============================] - 5s 5ms/step - loss: 0.6917 - accuracy: 0.5302
Epoch 42/50
858/858 [==============================] - 5s 6ms/step - loss: 0.6915 - accuracy: 0.5302
Epoch 43/50
858/858 [==============================] - 5s 5ms/step - loss: 0.6916 - accuracy: 0.5286
Epoch 44/50
858/858 [==============================] - 7s 8ms/step - loss: 0.6917 - accuracy: 0.5302
Epoch 45/50
858/858 [==============================] - 4s 5ms/step - loss: 0.6916 - accuracy: 0.5302
Epoch 46/50
858/858 [==============================] - 2s 3ms/step - loss: 0.6916 - accuracy: 0.5292
Epoch 47/50
858/858 [==============================] - 2s 2ms/step - loss: 0.6918 - accuracy: 0.5302
Epoch 48/50
858/858 [==============================] - 3s 4ms/step - loss: 0.6916 - accuracy: 0.5286
Epoch 49/50
858/858 [==============================] - 3s 3ms/step - loss: 0.6918 - accuracy: 0.5302
Epoch 50/50
858/858 [==============================] - 2s 2ms/step - loss: 0.6917 - accuracy: 0.5302

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 1.7128 - accuracy: 0.5401 - 491ms/epoch - 2ms/step
Loss: 1.7128208875656128, Accuracy: 0.5400874614715576

In [ ]:
# Export our model to HDF5 file
# nn.save("Alphabet_Soup_Analysis.h5")